MARKETS = {
    "United States": {
        "currency": "USD",
        "timezone": "America/New_York",
        "exchange_suffix": "",
        "indices": {
            "S&P 500": {
                "yahoo_symbol": "^GSPC",
                "description": "500 large-cap US companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
                "wiki_table_index": 0,
                "ticker_column": "Symbol",
                "ticker_suffix": "",
                "fix_dots": True,
                "min_rows": 490,
            },
            "NASDAQ 100": {
                "yahoo_symbol": "^NDX",
                "description": "100 largest non-financial NASDAQ companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/Nasdaq-100",
                "wiki_table_index": None,
                "ticker_column": "Ticker",
                "ticker_suffix": "",
                "min_rows": 95,
            },
            "Dow Jones": {
                "yahoo_symbol": "^DJI",
                "description": "30 blue-chip US companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average",
                "wiki_table_index": None,
                "ticker_column": "Symbol",
                "ticker_suffix": "",
                "min_rows": 28,
            },
            "Russell 2000": {
                "yahoo_symbol": "^RUT",
                "description": "Small-cap index (representative sample)",
                "source_type": "static",
                "static_tickers": [
                    "ACMR", "ADMA", "AEIS", "AGIO", "ALKT", "AMN", "AMPH", "AMRX",
                    "ANIP", "APOG", "ARHS", "ARLO", "ATEX", "ATSG", "AVNS", "BCPC",
                    "BFST", "BLBD", "BOOT", "CBZ", "CABA", "CARG", "CASH", "CHUY",
                    "CLFD", "CMCO", "CNMD", "CODI", "CONN", "BRP",
                ],
            },
        },
    },

    "India": {
        "currency": "INR",
        "timezone": "Asia/Kolkata",
        "exchange_suffix": ".NS",
        "indices": {
            "NIFTY 50": {
                "yahoo_symbol": "^NSEI",
                "description": "50 largest NSE-listed companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/NIFTY_50",
                "wiki_table_index": None,
                "ticker_column": "Symbol",
                "ticker_suffix": ".NS",
                "min_rows": 45,
            },
            "NIFTY 100": {
                "yahoo_symbol": "^CNX100",
                "description": "100 largest NSE-listed companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/NIFTY_100",
                "wiki_table_index": None,
                "ticker_column": "Symbol",
                "ticker_suffix": ".NS",
                "min_rows": 90,
            },
            "SENSEX": {
                "yahoo_symbol": "^BSESN",
                "description": "30 largest BSE-listed companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/BSE_SENSEX",
                "wiki_table_index": None,
                "ticker_column": "Symbol",
                "ticker_suffix": ".BO",
                "min_rows": 25,
            },
        },
    },

    "Singapore": {
        "currency": "SGD",
        "timezone": "Asia/Singapore",
        "exchange_suffix": ".SI",
        "indices": {
            "STI": {
                "yahoo_symbol": "^STI",
                "description": "30 largest SGX-listed companies",
                "source_type": "static",
                "static_tickers": [
                    "D05.SI", "O39.SI", "U11.SI", "Z74.SI", "S68.SI",
                    "C6L.SI", "9CI.SI", "A17U.SI", "BN4.SI", "G13.SI",
                    "C52.SI", "U96.SI", "H78.SI", "ME8U.SI", "N2IU.SI",
                    "BUOU.SI", "C38U.SI", "T82U.SI", "U14.SI", "Y92.SI",
                    "S58.SI", "V03.SI", "S63.SI", "J36.SI", "F34.SI",
                    "BS6.SI", "J69U.SI", "P40U.SI", "AWX.SI", "EB5.SI",
                ],
            },
        },
    },

    "United Kingdom": {
        "currency": "GBP",
        "timezone": "Europe/London",
        "exchange_suffix": ".L",
        "indices": {
            "FTSE 100": {
                "yahoo_symbol": "^FTSE",
                "description": "100 largest UK-listed companies",
                "source_type": "wikipedia",
                "wiki_url": "https://en.wikipedia.org/wiki/FTSE_100_Index",
                "wiki_table_index": None,
                "ticker_column": "Ticker",
                "ticker_suffix": ".L",
                "min_rows": 95,
            },
        },
    },
}
